baseURL = "http://robinforest.net/"
languageCode = "en-us"
title = "Programming and Photography"

# Tranquilpeak
# Version : 0.3.1-BETA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

defaultContentLanguage = "en-us"
theme = "tranquilpeak"
disqusShortname = "robinhu"
googleAnalytics = "UA-105698075-1"
paginate = 7
canonifyurls = true

[permalinks]
  post = "/post/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Robin Hu"
  bio = "I'm a computer programmer who also loves photography and juggling! Feel free to ask me any questions."
  job = "Software Developer"
  location = "New York City"
  email = "robinfhu@gmail.com"
  github = "http://github.com/robinfhu"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  #gravatarEmail = "thibaud.lepretre@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "/images/profile-pic.jpg"
  # Your Twitter username without the @. E.g : thibaudlepretre
  # twitter = "thibaudlepretre"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"

# Menu Configuration
[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\" title='Home'></i>"
  url = "/"
[[menu.main]]
  weight = 1
  identifier = "post"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-text-o\" title='Blog'></i>"
  url = "/post"
[[menu.main]]
  weight = 2
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-area-chart\" title='Projects'></i>"
  url = "/categories/projects"
[[menu.main]]
  weight = 3
  identifier = "photography"
  name = "Photography"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-camera\", title='Photography'></i>"
  url = "/categories/photography"
[[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-user\", title='About'></i>"
  url = "/about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\" title='Github'></i>"
  url = "https://github.com/robinfhu"
[[menu.links]]
  weight = 2
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-instagram\" title='Instagram'></i>"
  url = "https://instagram.com/robinfhu"
[[menu.links]]
  weight = 3
  identifier = "flickr"
  name = "Flickr"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-flickr\", title='Flickr'></i>"
  url = "https://www.flickr.com/photos/robinfhu"
[[menu.links]]
  weight = 4
  identifier = "facebook"
  name = "Facebook"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-facebook\", title='Facebook'></i>"
  url = "https://www.facebook.com/robinfhu"
[[menu.links]]
  weight = 10
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\" title='LinkedIn'></i>"
  url = "https://www.linkedin.com/in/robin-hu-5126923b"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["programming", "photography", "juggling", "software", "blog"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "Robin Hu: Computer Programmer | Photographer | Juggler"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 2

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage = "bokeh-cover.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

  # Your favicon path, default is "/favicon.png"
  favicon = "/favicon.png"

  # Header configuration
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #     url: /#search
  #     icon: search
  #     class: st-search-show-outputs

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  customCSS = ["css/main.css", "projects/charting/forest-d3.css"]

  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
  # customJS = ["js/foo.js"]

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  # Customize link of author avatar in sidebar
  # [params.sidebar.profile]
  #   url = "/#about"

  # Customize copyright value "© 2016 <CUSTOMIZATION>. All Rights Reserved"
  # [params.footer]
  #   copyright = "<a href=\"https://github.com/kakawait\">kakawait</a>"

